[plugin]

# If plugin should write debug messages in console
debug = false

# SQL

[sql]
hostname = "hostname"
database = "database"
username = "username"
password = "password"

[sql.settings]
minimumConnections = 2
maximumConnections = 6
timeout = 30000

# Autologin

[autologin.connectivity]
connectTimeout = 3000
readTimeout = 3000

[autologin.messages]
invalidNick = "&cTento nick obsahuje neplatné znaky!"
invalidToken = "&cVypadá to, že se snažíš připojit s warez na originální nick - připoj se znovu."
authServerNotFound = "&cNebyl nalezený žádný autentikační server.\n§cProsím, ihned nás kontaktuj.\n\n§9Discord: §ehttps://discord.gg/craftmania"
databaseError = "§e[AUTOLOGIN] &cNastala chyba při načítání dat z databáze.\n§cProsím, zkus se připojit znovu. Pokud by to stále nešlo, prosím, kontaktuj nás.\n\n§9Discord: §ehttps://discord.gg/craftmania"
runtimeError = "§e[AUTOLOGIN] &cNastala neočekávaná chyba.\n§cProsím, zkus se připojit znovu. Pokud by to stále nešlo, prosím, kontaktuj nás.\n\n§9Discord: §ehttps://discord.gg/craftmania"

[autologin.servers]
auth = "whub"
lobbies = ["lobby"]
