[plugin]

# If plugin should write debug messages in console
debug = false

# SQL

[sql]
hostname = "hostname"
database = "database"
username = "username"
password = "password"

[sql.settings]
minimumConnections = 2
maximumConnections = 6
timeout = 30000

# Autologin

[autologin.cache]
invalidateMineToolsCacheAfter = 1800000
invalidateAutologinCacheAfter = 3600000
invalidateDisabledAutologinCacheAfter = 3600000

[autologin.messages]
invalidNick = "§cTento nick obsahuje neplatné znaky!"
invalidToken = "§cVypadá to, že se snažíš připojit s warez na originální nick - připoj se znovu."
authServerNotFound = "§cNebyl nalezený žádný autentikační server.\n§cProsím, ihned nás kontaktuj.\n\n§9Discord: §ehttps://discord.gg/craftmania"
databaseError = "§e[AUTOLOGIN] §cNastala chyba při načítání dat z databáze.\n§cProsím, zkus se připojit znovu. Pokud by to stále nešlo, prosím, kontaktuj nás.\n\n§9Discord: §ehttps://discord.gg/craftmania"
runtimeError = "§e[AUTOLOGIN] §cNastala neočekávaná chyba.\n§cProsím, zkus se připojit znovu. Pokud by to stále nešlo, prosím, kontaktuj nás.\n\n§9Discord: §ehttps://discord.gg/craftmania"
autologinEnabled = "§e[AUTOLOGIN] §aÚspěšně sis zapnul autologin! §eProsím, připoj se znovu."
autologinDisabled = "§e[AUTOLOGIN] §aÚspěšně sis vypnul autologin! §eProsím, připoj se znovu."
autologinEnabledForced = "§e[AUTOLOGIN] §7Byl ti §azapnut§7 autologin. §eProsím, připoj se znovu."
autologinDisabledForced = "§e[AUTOLOGIN] §7Byl ti §cvypnut§7 autologin. §eProsím, připoj se znovu."

[autologin.servers]
auth = "whub"
lobbies = ["lobby"]

# Misc

[pumpk1n]
dataFolder = "./pumpk1n/"