name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GPR_USER: ${{ secrets.GPR_USER }}
      GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Build plugin
        run: ./gradlew shadowJar -PGPR_USER=$GPR_USER -PGPR_TOKEN=$GPR_TOKEN
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Artifacts
          path: build/libs